controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_roll_joint
      - wrist_pitch_joint